# 数据源配置
spring:
  datasource:
    druid:
      # 数据源 account
      account:
        url: jdbc:mysql://127.0.0.1:3306/xa_account?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始化连接大小：连接池建立时创建的初始化连接数
        initial-size: 5
        # 最小空闲数 连接池中最小的活跃连接数
        min-idle: 15
        #最大连接数:连接池中最大的活跃连接数
        max-active: 60
        validation-query: SELECT 1
        #获取连接时检测：是否在获得连接后检测其可用性
        test-on-borrow: true
        #空闲时检测：是否在连接空闲一段时间后检测其可用性
        test-while-idle: true
        #连接保持空闲而不被驱逐的最长时间
        time-between-eviction-runs-millis: 60000
      #数据源 redpacket
      redpacket:
        url: jdbc:mysql://127.0.0.1:3306/xa_red_account?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始化连接大小：连接池建立时创建的初始化连接数
        initial-size: 5
        # 最小空闲数 连接池中最小的活跃连接数
        min-idle: 15
        #最大连接数:连接池中最大的活跃连接数
        max-active: 60
        validation-query: SELECT 1
        #获取连接时检测：是否在获得连接后检测其可用性
        test-on-borrow: true
        #空闲时检测：是否在连接空闲一段时间后检测其可用性
        test-while-idle: true
        #连接保持空闲而不被驱逐的最长时间
        time-between-eviction-runs-millis: 60000
      # 合并多个datasource监控
      use-global-data-source-stat: true
      #配置druid显示监控统计信息
      #开启Druid的监控平台 http://localhost:9090/druid
      #1. StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow:
        deny:
      #2. WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
  #Spring Boot2.1以上 默认禁用那种bean覆盖(作用 用于兼容低版本)
  main:
    allow-bean-definition-overriding: true